"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import type { MenuCategoryDto, ProductDto, ProductLocationDto } from "@/types/menu";

type LocationOption = { id: string; name: string; status: string };

async function apiError(response: Response, fallback: string) { const body: unknown = await response.json().catch(() => null); return typeof body === "object" && body && "error" in body && typeof body.error === "string" ? body.error : fallback; }

export function MenuProductEditor({ product, categories, locations, canEditCatalog }: { product: ProductDto; categories: MenuCategoryDto[]; locations: LocationOption[]; canEditCatalog: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [imageUrl, setImageUrl] = useState(product.imageUrl);
  const assignments = new Map(product.locations.map((entry) => [entry.locationId, entry]));

  async function saveIdentity(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const data = new FormData(event.currentTarget); const payload = { name: String(data.get("name")), slug: String(data.get("slug")), categoryId: String(data.get("categoryId")), description: String(data.get("description")), sku: String(data.get("sku") || "") || null, status: String(data.get("status")), sortOrder: Number(data.get("sortOrder")) }; try { const response = await fetch(`/api/admin/menu/products/${product.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(await apiError(response, "The product could not be updated.")); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The product could not be updated."); } finally { setBusy(false); } }
  async function saveLocation(locationId: string, event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const data = new FormData(event.currentTarget); try { const response = await fetch(`/api/admin/menu/products/${product.id}/locations/${locationId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ price: String(data.get("price")), currencyCode: String(data.get("currencyCode")), isAvailable: data.get("isAvailable") === "on" }) }); if (!response.ok) throw new Error(await apiError(response, "The location offer could not be saved.")); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The location offer could not be saved."); } finally { setBusy(false); } }
  async function replaceImage(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get("image"); if (!(file instanceof File) || !file.size) return; setBusy(true); setError(null); try { const body = new FormData(); body.set("image", file); const response = await fetch(`/api/admin/menu/products/${product.id}/image`, { method: "PUT", body }); if (!response.ok) throw new Error(await apiError(response, "The image could not be uploaded.")); const result = await response.json() as { imageUrl: string }; setImageUrl(result.imageUrl); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The image could not be uploaded."); } finally { setBusy(false); } }
  async function removeImage() { setBusy(true); setError(null); try { const response = await fetch(`/api/admin/menu/products/${product.id}/image`, { method: "DELETE" }); if (!response.ok) throw new Error(await apiError(response, "The image could not be removed.")); setImageUrl(null); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The image could not be removed."); } finally { setBusy(false); } }

  return <div className="mt-7 space-y-6">
    {!canEditCatalog ? <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-100">Global product fields are read-only. You may update only your authorized location offers.</div> : null}
    {error ? <p role="alert" className="text-sm text-red-300">{error}</p> : null}
    <section className="grid gap-6 lg:grid-cols-[18rem_1fr]">
      <div className="cb-panel overflow-hidden"><div className="relative aspect-square bg-zinc-950">{imageUrl ? <Image src={imageUrl} alt={`${product.name} product`} fill sizes="288px" className="object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-zinc-700">No product image</div>}</div>{canEditCatalog ? <form onSubmit={replaceImage} className="space-y-3 p-4"><label className="block text-xs text-zinc-400">Replace image<input name="image" type="file" accept="image/jpeg,image/png,image/webp" className="cb-field mt-2 text-xs" required /></label><button disabled={busy} className="cb-button-secondary w-full">Upload image</button>{imageUrl ? <button type="button" disabled={busy} onClick={() => void removeImage()} className="cb-button-danger w-full">Remove image</button> : null}</form> : null}</div>
      <form onSubmit={saveIdentity} className="cb-panel grid gap-4 p-5 sm:grid-cols-2 sm:p-7"><Field label="Name"><input name="name" defaultValue={product.name} className="cb-field" disabled={!canEditCatalog || busy} required /></Field><Field label="Slug"><input name="slug" defaultValue={product.slug} className="cb-field font-mono" disabled={!canEditCatalog || busy} required /></Field><Field label="Category"><select name="categoryId" defaultValue={product.categoryId} className="cb-field" disabled={!canEditCatalog || busy}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="SKU"><input name="sku" defaultValue={product.sku ?? ""} className="cb-field uppercase" disabled={!canEditCatalog || busy} /></Field><Field label="Status"><select name="status" defaultValue={product.status} className="cb-field" disabled={!canEditCatalog || busy}><option>ACTIVE</option><option>INACTIVE</option></select></Field><Field label="Sort order"><input name="sortOrder" type="number" min={0} max={10000} defaultValue={product.sortOrder} className="cb-field" disabled={!canEditCatalog || busy} /></Field><Field label="Description" wide><textarea name="description" defaultValue={product.description} className="cb-field min-h-28" disabled={!canEditCatalog || busy} required /></Field>{canEditCatalog ? <button disabled={busy} className="cb-button-primary sm:col-start-2">Save product</button> : null}</form>
    </section>
    <section><h2 className="text-xl font-semibold text-zinc-100">Location pricing & availability</h2><p className="mt-1 text-sm text-zinc-500">Product status and location availability are intentionally independent.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{locations.map((location) => <LocationOffer key={location.id} location={location} assignment={assignments.get(location.id)} busy={busy} onSave={saveLocation} />)}</div>{locations.length === 0 ? <div className="cb-panel mt-4 p-7 text-sm text-zinc-500">This product is not currently sold at any location accessible to you.</div> : null}</section>
  </div>;
}

function LocationOffer({ location, assignment, busy, onSave }: { location: LocationOption; assignment?: ProductLocationDto; busy: boolean; onSave(id: string, event: FormEvent<HTMLFormElement>): Promise<void> }) { return <form onSubmit={(event) => void onSave(location.id, event)} className="cb-panel p-5"><div className="flex items-center justify-between"><h3 className="font-medium text-zinc-100">{location.name}</h3><span className="text-xs text-zinc-500">{assignment ? "Assigned" : "Not assigned"}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Price"><input name="price" defaultValue={assignment?.price ?? "0.00"} className="cb-field" inputMode="decimal" required /></Field><Field label="Currency"><input name="currencyCode" defaultValue={assignment?.currencyCode ?? "USD"} maxLength={3} className="cb-field uppercase" required /></Field></div><label className="mt-4 flex items-center gap-2 text-sm text-zinc-300"><input name="isAvailable" type="checkbox" defaultChecked={assignment?.isAvailable ?? true} /> Available at this location</label><button disabled={busy} className="cb-button-secondary mt-5 w-full">{assignment ? "Save offer" : "Assign product"}</button></form>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`text-sm text-zinc-300 ${wide ? "sm:col-span-2" : ""}`}>{label}<span className="mt-2 block">{children}</span></label>; }
