"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { useNotifications } from "@/components/ui/notification-provider";
import type { MovieDto } from "@/types/screening";

async function message(response: Response, fallback: string) { const body: unknown = await response.json().catch(() => null); return typeof body === "object" && body && "error" in body && typeof body.error === "string" ? body.error : fallback; }

export function MovieEditor({ movie, canEdit }: { movie: MovieDto; canEdit: boolean }) {
  const router = useRouter(); const notifications = useNotifications(); const [busy, setBusy] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { const response = await fetch(`/api/admin/movies/${movie.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: data.get("title"), slug: data.get("slug"), synopsis: data.get("synopsis"), durationMinutes: data.get("durationMinutes"), language: data.get("language"), contentRating: data.get("contentRating"), status: data.get("status") }) }); if (!response.ok) throw new Error(await message(response, "The movie could not be saved.")); notifications.success("Movie saved successfully."); router.push("/admin"); } catch (error) { notifications.error(error instanceof Error ? error.message : "The movie could not be saved."); } finally { setBusy(false); } }
  async function poster(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get("poster"); if (!(file instanceof File) || !file.size) return; setBusy(true); const body = new FormData(); body.set("poster", file); try { const response = await fetch(`/api/admin/movies/${movie.id}/poster`, { method: "PUT", body }); if (!response.ok) throw new Error(await message(response, "The poster could not be uploaded.")); notifications.success("Poster uploaded successfully."); router.push("/admin"); } catch (error) { notifications.error(error instanceof Error ? error.message : "The poster could not be uploaded."); } finally { setBusy(false); } }
  async function removePoster() { setBusy(true); try { const response = await fetch(`/api/admin/movies/${movie.id}/poster`, { method: "DELETE" }); if (!response.ok) throw new Error(await message(response, "The poster could not be removed.")); notifications.success("Poster removed successfully."); router.push("/admin"); } catch (error) { notifications.error(error instanceof Error ? error.message : "The poster could not be removed."); } finally { setBusy(false); } }
  return <div className="mt-7 grid gap-6 lg:grid-cols-[18rem_1fr]"><aside className="cb-panel overflow-hidden"><div className="relative aspect-[2/3] bg-zinc-950">{movie.posterUrl ? <Image src={movie.posterUrl} alt={`${movie.title} poster`} fill sizes="288px" className="object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-zinc-700">No poster</div>}</div>{canEdit ? <form onSubmit={poster} className="space-y-3 p-4"><label className="block text-xs text-zinc-400">Replace poster<input name="poster" type="file" accept="image/jpeg,image/png,image/webp" className="cb-field mt-2 text-xs" required /></label><button disabled={busy} className="cb-button-secondary w-full">Upload poster</button>{movie.posterUrl ? <button type="button" disabled={busy} onClick={() => void removePoster()} className="cb-button-danger w-full">Remove poster</button> : null}</form> : null}</aside><form onSubmit={save} className="cb-panel grid gap-5 p-5 sm:grid-cols-2 sm:p-7"><label className="text-sm text-zinc-300">Title<input name="title" defaultValue={movie.title} disabled={!canEdit || busy} className="cb-field mt-2" required /></label><label className="text-sm text-zinc-300">Slug<input name="slug" defaultValue={movie.slug} disabled={!canEdit || busy} className="cb-field mt-2 font-mono" required /></label><label className="text-sm text-zinc-300">Runtime<input name="durationMinutes" type="number" min={1} max={600} defaultValue={movie.durationMinutes} disabled={!canEdit || busy} className="cb-field mt-2" required /></label><label className="text-sm text-zinc-300">Language<input name="language" defaultValue={movie.language ?? ""} disabled={!canEdit || busy} className="cb-field mt-2" /></label><label className="text-sm text-zinc-300">Content rating<input name="contentRating" defaultValue={movie.contentRating ?? ""} disabled={!canEdit || busy} className="cb-field mt-2" /></label><label className="text-sm text-zinc-300">Status<select name="status" defaultValue={movie.status} disabled={!canEdit || busy} className="cb-field mt-2"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="text-sm text-zinc-300 sm:col-span-2">Synopsis<textarea name="synopsis" defaultValue={movie.synopsis ?? ""} disabled={!canEdit || busy} className="cb-field mt-2 min-h-36" /></label>{canEdit ? <button disabled={busy} className="cb-button-primary sm:col-start-2">Save movie</button> : <p className="sm:col-span-2 text-sm text-amber-200">Movie metadata is read-only for Location Managers.</p>}</form></div>;
}
