"use client";
import { useEffect, useRef, useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import { useNotifications } from "@/components/ui/notification-provider";
import { trapDialogFocus } from "@/components/ui/dialog-focus";
type Preview = { counts: { unpaidPlaced: number; paidPlaced: number; started: number; delivered: number; canceled: number }; more: boolean; batchLimit: number; batchOrderIds: string[] };
export function ScreeningReconciliation({ screeningId }: { screeningId: string }) {
  const [preview, setPreview] = useState<Preview | null>(null), [busy, setBusy] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null), active = useRef(false), notifications = useNotifications(), reduced = useReducedMotion();
  const endpoint = `/api/admin/screenings/${screeningId}/reconciliation`;
  useEffect(() => { const controller = new AbortController(); void fetch(endpoint, { cache: "no-store", signal: controller.signal }).then(r => r.ok ? r.json() : null).then(result => { if (!controller.signal.aborted) setPreview(result); }).catch(() => undefined); return () => controller.abort(); }, [endpoint]);
  if (!preview) return null;
  return <motion.section layout={!reduced} className="cb-panel mt-6 p-6"><p className="text-xs uppercase tracking-widest text-amber-300">Canceled screening · Order reconciliation</p><h2 className="mt-3 text-xl font-semibold">Review affected orders</h2><p className="mt-3 text-sm text-zinc-400">Preview is bounded to {preview.batchLimit} orders. Execution rechecks every order under a lock. Repeat safely for remaining batches.</p><dl className="mt-5 grid gap-3 sm:grid-cols-3">{[["Unpaid placed · Cancel payment safely", preview.counts.unpaidPlaced], ["Paid placed · Cancel, refund & restore", preview.counts.paidPlaced], ["Started · Supervisor issue, no restock", preview.counts.started], ["Delivered · Preserve, no automatic refund", preview.counts.delivered], ["Already canceled · No repeated effects", preview.counts.canceled]].map(([label, value]) => <div key={label} className="rounded-xl bg-zinc-950 p-4"><dt className="text-xs text-zinc-400">{label}</dt><dd className="mt-2 text-2xl font-semibold">{value}</dd></div>)}</dl>{preview.more ? <p className="mt-3 text-sm text-amber-300">More orders exist; execute reviewed batches until reconciled.</p> : null}<button onClick={() => dialog.current?.showModal()} className="cb-button-primary mt-5 min-h-12">Review reconciliation</button><dialog onKeyDown={trapDialogFocus} ref={dialog} aria-labelledby="reconciliation-title" className="fixed inset-0 m-auto w-[calc(100%_-_2rem)] max-w-md rounded-2xl border border-zinc-600 bg-zinc-900 p-6 text-white backdrop:bg-black/75" onCancel={e => { if (busy) e.preventDefault(); }}><h3 id="reconciliation-title" className="text-xl font-semibold">Reconcile canceled screening?</h3><p className="mt-4 text-sm leading-6 text-zinc-400">Cancel eligible placed orders and initiate remaining refunds. Started food becomes a supervisor issue. Delivered orders are unchanged. Stock restoration uses original consumption only.</p><button autoFocus disabled={busy} onClick={() => dialog.current?.close()} className="cb-button-secondary mt-5 min-h-12 w-full">Go back</button><button disabled={busy} className="cb-button-primary mt-3 min-h-12 w-full" onClick={async () => {
    if (active.current) return; active.current = true; setBusy(true);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmed: true, batchOrderIds: preview.batchOrderIds }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setPreview(body.preview); notifications.success("Reconciliation saved. Provider refunds may still be processing."); dialog.current?.close(); }
    catch (error) { notifications.error(error instanceof Error ? error.message : "Reconciliation failed."); }
    finally { active.current = false; setBusy(false); }
  }}>{busy ? "Reconciling…" : "Confirm reviewed batch"}</button></dialog></motion.section>;
}
