import Link from "next/link";

import { StockStatusBadge } from "@/components/admin/stock-status-badge";
import { PageTransition } from "@/components/super-admin/page-transition";
import { StatCard } from "@/components/super-admin/stat-card";
import { formatInventoryQuantity, inventoryUnitLabel, movementTypeLabel } from "@/lib/inventory/format";
import { getInventoryOverview } from "@/server/services/inventory.service";

export const metadata = { title: "Inventory" };

export default async function InventoryOverviewPage({ searchParams }: { searchParams: Promise<{ locationId?: string }> }) {
  const { locationId } = await searchParams;
  const overview = await getInventoryOverview(locationId);
  return <PageTransition>
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold tracking-[.18em] text-amber-400 uppercase">Stock control</p><h1 className="mt-2 text-3xl font-semibold text-zinc-50">Inventory overview</h1><p className="mt-2 text-sm text-zinc-400">Authoritative per-location stock, thresholds, and immutable movement history.</p></div><div className="flex flex-wrap gap-3"><Link href="/admin/inventory/movements" className="cb-button-secondary">Movement history</Link><Link href="/admin/inventory/items" className="cb-button-primary">Item catalog</Link></div></header>
    <form className="cb-panel mt-7 flex flex-col gap-3 p-4 sm:flex-row sm:items-end"><label className="min-w-0 flex-1 text-sm text-zinc-300">Selected location<select name="locationId" defaultValue={overview.selectedLocationId ?? ""} className="cb-field mt-2">{overview.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><button className="cb-button-secondary">View location</button>{overview.selectedLocationId ? <Link href={`/admin/inventory/locations/${overview.selectedLocationId}`} className="cb-button-primary text-center">Manage stock</Link> : null}</form>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><StatCard label="Configured items" value={overview.total} detail="Tracked at selected location" index={0} /><StatCard label="Low stock" value={overview.lowStock} detail="At or below threshold" index={1} /><StatCard label="Out of stock" value={overview.outOfStock} detail="No quantity on hand" tone="danger" index={2} /></section>
    <section className="mt-8"><h2 className="text-lg font-semibold text-zinc-100">Stock snapshot</h2><div className="mt-4 cb-panel overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="border-b border-zinc-800 text-xs uppercase tracking-wider text-zinc-600"><tr><th className="px-5 py-3">Item</th><th className="px-5 py-3">On hand</th><th className="px-5 py-3">Threshold</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-zinc-800">{overview.inventory.map((item) => <tr key={item.id}><td className="px-5 py-4"><span className="font-medium text-zinc-100">{item.itemName}</span><span className="ml-2 font-mono text-xs text-zinc-600">{item.sku}</span></td><td className="px-5 py-4 text-zinc-300">{formatInventoryQuantity(item.quantityOnHand)} {inventoryUnitLabel[item.unit]}</td><td className="px-5 py-4 text-zinc-400">{formatInventoryQuantity(item.lowStockThreshold)} {inventoryUnitLabel[item.unit]}</td><td className="px-5 py-4"><StockStatusBadge status={item.stockStatus} /></td></tr>)}</tbody></table>{overview.inventory.length === 0 ? <p className="p-8 text-center text-sm text-zinc-500">No inventory items configured for this location.</p> : null}</div></section>
    <section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-zinc-100">Recent movements</h2><Link href="/admin/inventory/movements" className="text-sm text-amber-300">View all</Link></div><div className="mt-4 space-y-3">{overview.movements.map((movement) => <div key={movement.id} className="cb-panel flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="font-medium text-zinc-100">{movement.itemName}</p><p className="mt-1 text-xs text-zinc-500">{movementTypeLabel[movement.type]} · {movement.actorDisplayName}</p></div><div className="text-right"><p className={movement.quantityDelta.startsWith("-") ? "font-mono text-red-300" : "font-mono text-emerald-300"}>{movement.quantityDelta.startsWith("-") ? "" : "+"}{formatInventoryQuantity(movement.quantityDelta)} {inventoryUnitLabel[movement.unit]}</p><time className="mt-1 block text-xs text-zinc-600">{new Date(movement.createdAt).toLocaleString()}</time></div></div>)}</div></section>
  </PageTransition>;
}
