export type ServiceErrorCode =
  | "AUTHENTICATION_REQUIRED"
  | "AUTHORIZATION_DENIED"
  | "DUPLICATE_ADMIN_EMAIL"
  | "DUPLICATE_ORGANIZATION_SLUG"
  | "DUPLICATE_LOCATION_SLUG"
  | "ORGANIZATION_NOT_FOUND"
  | "ORGANIZATION_NOT_ACTIVE"
  | "TENANT_CONTEXT_MISSING"
  | "LOCATION_ACCESS_DENIED"
  | "LOCATION_CREATION_DENIED"
  | "LOCATION_NOT_FOUND"
  | "LOCATION_NOT_ACTIVE"
  | "DUPLICATE_HALL_NUMBER"
  | "HALL_NOT_FOUND"
  | "HALL_NOT_ACTIVE"
  | "DUPLICATE_SEAT"
  | "SEAT_NOT_FOUND"
  | "NO_STATUS_CHANGE"
  | "ONBOARDING_FAILED"
  | "CATEGORY_NOT_FOUND"
  | "DUPLICATE_CATEGORY_SLUG"
  | "PRODUCT_NOT_FOUND"
  | "DUPLICATE_PRODUCT_SLUG"
  | "DUPLICATE_PRODUCT_SKU"
  | "PRODUCT_LOCATION_CONFLICT"
  | "IMAGE_UPLOAD_INVALID"
  | "IMAGE_STORAGE_UNAVAILABLE"
  | "INVENTORY_ITEM_NOT_FOUND"
  | "DUPLICATE_INVENTORY_SKU"
  | "INVENTORY_UNIT_LOCKED"
  | "LOCATION_INVENTORY_NOT_FOUND"
  | "LOCATION_INVENTORY_CONFLICT"
  | "INSUFFICIENT_STOCK"
  | "RECIPE_COMPONENT_NOT_FOUND"
  | "RECIPE_COMPONENT_CONFLICT"
  | "MOVIE_NOT_FOUND"
  | "DUPLICATE_MOVIE_SLUG"
  | "POSTER_STORAGE_UNAVAILABLE"
  | "SCREENING_NOT_FOUND"
  | "SCREENING_OVERLAP"
  | "SCREENING_TIME_INVALID"
  | "SCREENING_EDIT_LOCKED"
  | "SCREENING_RESOURCE_INACTIVE"
  | "SEAT_QR_NOT_FOUND"
  | "SEAT_QR_ALREADY_EXISTS"
  | "SEAT_QR_REVOKED"
  | "SEAT_QR_STORAGE_UNAVAILABLE"
  | "NO_ACTIVE_SCREENING"
  | "CUSTOMER_SESSION_INVALID"
  | "CUSTOMER_SESSION_EXPIRED"
  | "CART_EMPTY"
  | "CART_INVALID"
  | "PRODUCT_UNAVAILABLE"
  | "PRICE_CHANGED"
  | "MIXED_CURRENCY"
  | "ORDER_NOT_FOUND"
  | "CHECKOUT_CONFLICT"
  | "INVALID_ORDER_TRANSITION"
  | "STALE_ORDER_STATE"
  | "ORDER_ALREADY_CLAIMED"
  | "ORDER_NOT_READY"
  | "NOT_ASSIGNED_TO_YOU"
  | "INVALID_DELIVERY_TRANSITION"
  | "UNAUTHORIZED_LOCATION"
  | "ORDER_ALREADY_DELIVERED";

export class ServiceError extends Error {
  constructor(
    readonly code: ServiceErrorCode,
    readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = "ServiceError";
  }
}

export function isServiceError(error: unknown): error is ServiceError {
  return error instanceof ServiceError;
}
